### ISSUE TITLE
Search project number and manager's name

### ISSUE THREAD

**Issue by MingboPeng** [tt-sus/qaqc#11]
![image](https://user-images.githubusercontent.com/9031066/28721645-0a173a00-737f-11e7-9fde-9749a818fcec.png)

**Comment by akshar07** [comment]
It will need 2 more input fields.

**Comment by akshar07** [comment]
done

**Comment by MingboPeng** [comment]
We talked about this, add a searchKey in each project's data table, to allow users to search the manager's name, project number, or name, without adding two more searching inputs.

**Comment by akshar07** [comment]
done
