### ISSUE TITLE
Sort by: Start Date, Due Date, and Updated Date

### ISSUE THREAD

**Issue by MingboPeng** [tt-sus/qaqc#16]
![image](https://user-images.githubusercontent.com/9031066/28734088-373c19f0-73ad-11e7-9ed4-d31fed8ddf6f.png)

Please reference Design Explorer
![image](https://user-images.githubusercontent.com/9031066/28734147-8609e44a-73ad-11e7-9e94-6c8506270075.png)

**Comment by akshar07** [comment]
dont want to complicate things-> 1 action for sorting. for select box there are 2 steps
